/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.CONEXION;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josh Bor
 */
public class frmEstado_cuenta extends javax.swing.JFrame implements Printable {
  FondoPanel fondo =new FondoPanel();
   CONEXION con = new CONEXION();
    Connection cn;
    PreparedStatement ps;
    Statement st;
    ResultSet rs; 
    DefaultTableModel md;
  
    /**
     * Creates new form frmEstado_cuenta
     */
    public frmEstado_cuenta() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        lblNomP.setVisible(false);
        lblsaldo_cuenta.setVisible(false);
        lblApPr.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNumCuenta = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEstado_cuenta = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblsaldo_cuenta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNomP = new javax.swing.JLabel();
        lblApPr = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("ESTADOS DE CUENTA ");

        pnlDatos.setBackground(new java.awt.Color(255, 255, 255));
        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("ESTADO DE CUENTA")));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("NUMERO DE CUENTA ");

        jScrollPane1.setViewportView(txtNumCuenta);

        tblEstado_cuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMERO DE TRANSACCION", "NUMERO DE CUENTA ", "NOMBRE DE CUENTA", "MOVIMIENTO", "MONTO", "DESCRIPCION", "FECHA"
            }
        ));
        jScrollPane2.setViewportView(tblEstado_cuenta);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("SALDO DE LA CUENTA");

        lblsaldo_cuenta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblsaldo_cuenta.setText("SALDO_CUENTA");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("PROPIETARIO DE LA CUENTA");

        lblNomP.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNomP.setText("NOMBRE");

        lblApPr.setText("apellido");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(lblsaldo_cuenta))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addComponent(lblNomP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblApPr, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(lblNomP)
                        .addComponent(lblApPr)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblsaldo_cuenta))
                .addContainerGap())
        );

        btnMostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMostrar.setText("MOSTRAR ");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnActualizar.setText("NUEVA CONSULTA");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnImprimir.setText("IMPRMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnMostrar)
                .addGap(41, 41, 41)
                .addComponent(btnActualizar)
                .addGap(49, 49, 49)
                .addComponent(btnImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnActualizar)
                    .addComponent(btnImprimir)
                    .addComponent(btnVolver))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed

  if(!txtNumCuenta.getText().equals("")){
                           
       estado_cuenta (txtNumCuenta.getText());
       saldo(txtNumCuenta.getText());
       nombre(txtNumCuenta.getText());        
        }else{
        JOptionPane.showMessageDialog(null,"Debe proporcionar un número de cuenta");
        }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    frmEstado_cuenta mostrar = new frmEstado_cuenta();
    mostrar.setVisible(true);
    this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
try{
          PrinterJob imp =PrinterJob.getPrinterJob();
          imp.setPrintable(this);
          boolean tp=imp.printDialog();
          if(tp){
         
              imp.print();
          }
          }catch(PrinterException pex){
 JOptionPane.showMessageDialog(null, "ERROR DE PROGRAMA","ERROR\n"+pex,JOptionPane.INFORMATION_MESSAGE);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
         vista_colaborador mostrar= new vista_colaborador();
         mostrar.setVisible(true);
         this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

     void estado_cuenta (String id_cuenta) {
        String sql = "select ID_TRANSACCION,ID_CUENTA,NOMBRE_CUENTA,MOVIMIENTO,MONTO,DESCRIPCION,FECHA \n" +
"from cuenta_transaccion CT inner join transaccion T \n" +
"on CT.TRANSACCION_ID_TRANSACCION=T.ID_TRANSACCION inner join cuenta C \n" +
"on CT.CUENTA_ID_CUENTA=C.ID_CUENTA where C.ID_CUENTA=?";
        try {
            cn = con.getConexion();
            ps = cn.prepareStatement(sql);
            ps.setString(1, id_cuenta);
            rs = ps.executeQuery();
            Object[] ROL = new Object[7];
            md = (DefaultTableModel) tblEstado_cuenta.getModel();
            while (rs.next()) {
                ROL[0] = rs.getInt("ID_TRANSACCION");
                ROL[1] = rs.getString("ID_CUENTA");
                ROL[2] = rs.getString("NOMBRE_CUENTA");
                ROL[3] = rs.getString("MOVIMIENTO");
                ROL[4] = rs.getInt("MONTO");
                ROL[5] = rs.getString("DESCRIPCION");
                ROL[6] = rs.getString("FECHA");
                md.addRow(ROL);
            }
            tblEstado_cuenta.setModel(md);
            cn.close();
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null," cuenta no encontrada");
        }
        
    }
     void saldo(String id_cuenta){
        
          String sql="select saldo from cuenta where ID_CUENTA= ?";
          try {
            cn = con.getConexion();
            ps = cn.prepareStatement(sql);
            ps.setString(1, id_cuenta);
            rs = ps.executeQuery();

            if (rs.next()) {
                lblsaldo_cuenta.setVisible(true);
                lblsaldo_cuenta.setText(rs.getString("saldo"));
            } else {
                JOptionPane.showMessageDialog(null, "Cuenta no encontrada");
            }
         cn.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }      
      }
     
     void nombre(String id_cuenta){
        
          String sql="select nombre, apellido  from cuenta "
      + "CU inner join persona PE on CU.PERSONA_ID_PERSONA=PE.ID_PERSONA where ID_CUENTA =?";
          try {
            cn = con.getConexion();
            ps = cn.prepareStatement(sql);
            ps.setString(1, id_cuenta);
            rs = ps.executeQuery();

            if (rs.next()) {
                lblNomP.setVisible(true);
                lblApPr.setVisible(true);
                lblNomP.setText(rs.getString("nombre"));
                lblApPr.setText(rs.getString("apellido"));
                
            } else {
                JOptionPane.showMessageDialog(null, "Cuenta no encontrada");
            }
         cn.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }      
      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEstado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEstado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEstado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEstado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEstado_cuenta().setVisible(true);
            }
        });
    }
@Override
    public int print(Graphics graf, PageFormat pagform, int index) throws PrinterException {
       
            if(index>0){
    return NO_SUCH_PAGE;
    
    }  
    Graphics2D hub= (Graphics2D) graf;
    hub.translate(pagform.getImageableX()+50,pagform.getImageableY()+50);
    hub.scale(0.5,0.5);
    
    pnlDatos.printAll(graf);
    return PAGE_EXISTS;
         
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApPr;
    private javax.swing.JLabel lblNomP;
    private javax.swing.JLabel lblsaldo_cuenta;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JTable tblEstado_cuenta;
    private javax.swing.JTextPane txtNumCuenta;
    // End of variables declaration//GEN-END:variables
}
